version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/simplify_url
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=simplify_url.settings.production
      - PORT=8000
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=90d6f931ca69073ba943e17446b52e8852e81555111c4e4ce1836470bcc3f209
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
