# Generated by Django 3.2.9 on 2022-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleurl',
            name='simple_url',
            field=models.URLField(default='https://example.com', verbose_name='Simple URL'),
        ),
    ]
