# Generated by Django 3.2.9 on 2022-07-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_app', '0002_alter_simpleurl_simple_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
    ]
