# Generated by Django 3.2.9 on 2022-07-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_app', '0003_alter_simpleurl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleurl',
            name='original_url',
            field=models.URLField(db_index=True, default='', verbose_name='URL to simplify'),
        ),
        migrations.AlterField(
            model_name='simpleurl',
            name='simple_url',
            field=models.URLField(default='', verbose_name='Simple URL'),
        ),
    ]
