# Generated by Django 3.2.9 on 2022-07-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_app', '0004_auto_20220715_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleurl',
            name='simple_url',
        ),
        migrations.AddField(
            model_name='simpleurl',
            name='simple_url_id',
            field=models.CharField(db_index=True, default='', max_length=10, verbose_name='Simple URL id'),
        ),
    ]
